/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.sample.starter;

import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
//import org.springframework.data.mongodb.repository.config.EnableMongoRepositories;

//@EnableMongoRepositories(basePackages = {"com.sample.starter.repository"})
@EnableJpaRepositories("com.sample.starter.repository")
@ComponentScan(basePackages = {"com.sample.starter"})
@SpringBootApplication(scanBasePackages = {"com.sample.starter","com.sample"})
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
  }

  // @Bean
  // ApplicationRunner applicationRunner(GreetingRepository greetingRepository) {
  //   return args -> {
  //     greetingRepository.save(new Greeting("kirve","pune"));
  //     greetingRepository.save(new Greeting("rushabh","mumbai")); 
  //   };
  // }

  // @Bean
  // public LocalContainerEntityManagerFactoryBean
  //   entityManagerFactory() throws URISyntaxException {
  //     LocalContainerEntityManagerFactoryBean entityManagerFactoryBean 
  //       = new LocalContainerEntityManagerFactoryBean();
  //     entityManagerFactoryBean.setDataSource
  //       ("jdbc:mysql://ec2-52-73-199-211.compute-1.amazonaws.com:5432");
  //     entityManagerFactoryBean.setPackagesToScan("com.sample.starter");
  //     //additional config of factory
  //     //entityManagerFactoryBean.setDataSource
  //     return entityManagerFactoryBean;
  // }

}
